### ISSUE TITLE
确认兼容性问题，完成版本升级

### ISSUE THREAD

**Issue by ZoruaFox** [TopRealm/MediaWiki#58]

**Comment by ZoruaFox** [comment]
https://youshou.wiki/load.php?lang=zh&modules=startup&only=scripts&raw=1&safemode=1&skin=vector
```php
[dd8c484db8ae6f6a5a45c480] /load.php?lang=zh&modules=startup&only=scripts&raw=1&safemode=1&skin=vector Error: Class "ResourceLoaderOOUIImageModule" not found

Backtrace:

from /www/wwwroot/MediaWiki/includes/ResourceLoader/ResourceLoader.php(416)
#0 /www/wwwroot/MediaWiki/includes/ResourceLoader/ResourceLoader.php(452): MediaWiki\ResourceLoader\ResourceLoader->getModule()
#1 /www/wwwroot/MediaWiki/includes/ResourceLoader/StartUpModule.php(172): MediaWiki\ResourceLoader\ResourceLoader->preloadModuleInfo()
#2 /www/wwwroot/MediaWiki/includes/ResourceLoader/StartUpModule.php(431): MediaWiki\ResourceLoader\StartUpModule->getModuleRegistrations()
#3 /www/wwwroot/MediaWiki/includes/ResourceLoader/Module.php(843): MediaWiki\ResourceLoader\StartUpModule->getScript()
#4 /www/wwwroot/MediaWiki/includes/ResourceLoader/Module.php(812): MediaWiki\ResourceLoader\Module->buildContent()
#5 /www/wwwroot/MediaWiki/includes/ResourceLoader/Module.php(955): MediaWiki\ResourceLoader\Module->getModuleContent()
#6 /www/wwwroot/MediaWiki/includes/ResourceLoader/ResourceLoader.php(686): MediaWiki\ResourceLoader\Module->getVersionHash()
#7 /www/wwwroot/MediaWiki/includes/ResourceLoader/ResourceLoader.php(786): MediaWiki\ResourceLoader\ResourceLoader->getCombinedVersion()
#8 /www/wwwroot/MediaWiki/includes/ResourceLoader/ResourceLoaderEntryPoint.php(54): MediaWiki\ResourceLoader\ResourceLoader->respond()
#9 /www/wwwroot/MediaWiki/includes/MediaWikiEntryPoint.php(200): MediaWiki\ResourceLoader\ResourceLoaderEntryPoint->execute()
#10 /www/wwwroot/MediaWiki/load.php(42): MediaWiki\MediaWikiEntryPoint->run()
#11 {main}
```
